package ru.boomearo.langhelper.versions;

public enum LangType {

    //Для поддержки остальных языков стоит просто добавлять еще енумов
    EN_US("en_us", false),
    AF_ZA("af_za", true),
    AR_SA("ar_sa", true),
    AST_E("ast_e", true),
    AZ_AZ("az_az", true),
    BA_RU("ba_ru", true),
    BAR("bar", true),
    BE_BY("be_by", true),
    BG_BG("bg_bg", true),
    BR_FR("br_fr", true),
    BRB("brb", true),
    BS_BA("bs_ba", true),
    CA_ES("ca_es", true),
    CS_CZ("cs_cz", true),
    CY_GB("cy_gb", true),
    DA_DK("da_dk", true),
    DE_AT("de_at", true),
    DE_CH("de_ch", true),
    DE_DE("de_de", true),
    EL_GR("el_gr", true),
    EN_AU("en_au", true),
    EN_CA("en_ca", true),
    EN_GB("en_gb", true),
    EN_NZ("en_nz", true),
    EN_PT("en_pt", true),
    EN_UD("en_ud", true),
    ENP("enp", true),
    ENWS("enws", true),
    EO_UY("eo_uy", true),
    ES_AR("es_ar", true),
    ES_CL("es_cl", true),
    ES_EC("es_ec", true),
    ES_ES("es_es", true),
    ES_MX("es_mx", true),
    ES_UY("es_uy", true),
    ES_VE("es_ve", true),
    ESAN("esan", true),
    ET_EE("et_ee", true),
    EU_ES("eu_es", true),
    FA_IR("fa_ir", true),
    FI_FI("fi_fi", true),
    FIL_PH("fil_ph", true),
    FO_FO("fo_fo", true),
    FR_CA("fr_ca", true),
    FR_FR("fr_fr", true),
    FRA_DE("fra_de", true),
    FY_NL("fy_nl", true),
    GA_IE("ga_ie", true),
    GD_GB("gd_gb", true),
    GL_ES("gl_es", true),
    GV_IM("gv_im", true),
    HAW_US("haw_us", true),
    HE_IL("he_il", true),
    HE_IN("hi_in", true),
    HR_HR("hr_hr", true),
    HU_HU("hu_hu", true),
    HY_AM("hy_am", true),
    IQ_NG("ig_ng", true),
    IO_EN("io_en", true),
    IS_IS("is_is", true),
    ISV("isv", true),
    IT_IT("it_it", true),
    JA_JP("ja_jp", true),
    JBO_EN("jbo_en", true),
    KA_GE("ka_ge", true),
    KK_KZ("kk_kz", true),
    KN_IN("kn_in", true),
    KO_KR("ko_kr", true),
    KSH("ksh", true),
    KW_GB("kw_gb", true),
    LA_LA("la_la", true),
    LB_LU("lb_lu", true),
    LI_LI("li_li", true),
    LOL_US("lol_us", true),
    LT_LT("lt_lt", true),
    LV_LV("lv_lv", true),
    MK_MK("mk_mk", true),
    MN_MN("mn_mn", true),
    MS_MY("ms_my", true),
    MT_MT("mt_mt", true),
    NDS_DE("nds_de", true),
    NL_BE("nl_be", true),
    NL_NL("nl_nl", true),
    NN_NO("nn_no", true),
    NO_NO("no_no", true),
    OC_FR("oc_fr", true),
    OVD("ovd", true),
    PL_PL("pl_pl", true),
    PT_BR("pt_br", true),
    PT_PT("pt_pt", true),
    QYA_AA("qya_aa", true),
    RO_RO("ro_ro", true),
    RPR("rpr", true),
    RU_RU("ru_ru", true),
    SCN("scn", true),
    SE_NO("se_no", true),
    SK_SK("sk_sk", true),
    SL_SI("sl_si", true),
    SO_SO("so_so", true),
    SQ_AL("sq_al", true),
    SR_SP("sr_sp", true),
    SV_SE("sv_se", true),
    SWG("swg", true),
    SXU("sxu", true),
    SZL("szl", true),
    TA_IN("ta_in", true),
    TH_TH("th_th", true),
    TL_PH("tl_ph", true),
    TLH_AA("tlh_aa", true),
    TR_TR("tr_tr", true),
    TT_RU("tt_ru", true),
    UK_UA("uk_ua", true),
    VAL_ES("val_es", true),
    VEC_IT("vec_it", true),
    VI_VN("vi_vn", true),
    YI_DE("yi_de", true),
    YO_NG("yo_ng", true),
    ZH_CN("zh_cn", true),
    ZH_HK("zh_hk", true),
    ZH_TW("zh_tw", true);

    private final String name;
    //Обозначает, является ли язык скачиваемым
    private final boolean external;

    LangType(String name, boolean external) {
        this.name = name;
        this.external = external;
    }

    public String getName() {
        return this.name;
    }

    public boolean isExternal() {
        return this.external;
    }
}
