name: LangHelper
main: ru.boomearo.langhelper.LangHelper
version: @version@
author: BoomEaro
description: LangHelper
api-version: 1.13
commands:
  langhelper:
    usage: /langhelper
    description: langhelper